GearUp/Controllers/LifePlanController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GearUp.Models;
using System;

namespace GearUp.Controllers
{
    [Authorize]
    public class LifePlanController : Controller
    {
        //lists that contain the information from the database
        List<string> needs = new List<string>();
        List<string> education = new List<string>();
        List<string> careerInputBox = new List<string>();
        List<string> careerDropDown = new List<string>();
        string studentAdvisor = "";
        List<string> academic = new List<string>();
        List<string> schoolGoals = new List<string>();
        List<string> career = new List<string>();
        List<string> careerType = new List<string>();


        public ActionResult Index()
        {
            ViewBag.Message = "LifePlans";

            return View();
        }

        public ActionResult Edit()
        {
            GearUpDBEntities db = new GearUpDBEntities();
            ViewBag.Message = "Your LifePlan edit page.";

            setViewBags();
            return View(db.Students);
        }


        /// <summary>
        /// Used to return information based on which submit button was pressed.
        /// 'submit' is the VALUE of the button pressed
        /// 'searchTerm' is used if the user is searching for a student.
        /// </summary>
        /// <param name="submit"></param>
        /// <param name="searchTerm"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(string submit, string searchTerm)
        {
            switch (submit)
            {
                case "Search":
                    return (SearchStudent(searchTerm));
                case "Submit":
                    //This will need a method that takes 3? lists containing the new 
                    //lifeplan info that will be added to the databse.
                    //Need to find out how the current information like student and avisor will
                    //be affected by this. (they may need to be found again...)
                    return View();
                //Other submit buttons go here.
                default:
                    setViewBags();
                    return View();
            }
        }





        /// <summary>
        /// Used to return a list of all students with the name like..
        /// </summary>
        /// <param name="term"></param>
        /// <returns></returns>
        public JsonResult GetStudents(string term)
        {
            GearUpDBEntities db = new GearUpDBEntities();
            List<string> students = db.Students.Where(s => s.firstName.StartsWith(term) || s.lastName.StartsWith(term))
                .Select(x => x.firstName + " " + x.lastName).ToList();

            return Json(students, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Used to return a list of all advisors with the name like...
        /// </summary>
        /// <param name="term"></param>
        /// <returns></returns>
        public JsonResult GetAdvisors(string term)
        {
            GearUpDBEntities db = new GearUpDBEntities();
            List<string> advisors = db.Advisors.Where(s => s.firstName.StartsWith(term) || s.lastName.StartsWith(term))
                .Select(x => x.firstName + " " + x.lastName).ToList();

            return Json(advisors, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This function is used to parse out the student search text box
        /// and return information on the student if that student exsits.
        /// 'name' is what the user entered in the text box.
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult SearchStudent(string name)
        {
            GearUpDBEntities db = new GearUpDBEntities();
            List<Student> students = null;

            if (!string.IsNullOrEmpty(name))
            {
                students = db.Students
                    .Where(s => s.firstName.StartsWith(name) || s.lastName.StartsWith(name)
                    || s.firstName + " " + s.lastName == name
                    || s.lastName + " " + s.firstName == name).ToList();
                if (students.Count == 1
                    && name.Equals(students[0].firstName + " " + students[0].lastName, StringComparison.InvariantCultureIgnoreCase)
                    || name.Equals(students[0].lastName + " " + students[0].firstName, StringComparison.InvariantCultureIgnoreCase))
                {
                    //Finds student's advisor's name for autofill
                    if (students[0].Advisor != null)
                    {
                        studentAdvisor = students[0].Advisor.firstName + " " + students[0].Advisor.lastName;
                    }


                    //update the right side of the form
                    //once we have db working then make calls to get this information
                    //for now going to make up data
                    needs.Add("FAFSA Help");
                    needs.Add("Math Tutoring");
                    needs.Add("ACT Prep");

                    education.Add("3.5 GPA");
                    education.Add("Graduate High Scool");
                    education.Add("Bachelor's Degree");

                    careerInputBox.Add("Programming");
                    careerInputBox.Add("Chef");
                    careerInputBox.Add("Start up own business");

                    careerDropDown.Add("Computers");
                    careerDropDown.Add("Culinary");
                    careerDropDown.Add("Business");

                }
            }
            setViewBags();
            return View();
        }

        [HttpPost]
        public ActionResult input(string academicNeeds)
        {
            List<string> academic = null;
            if (string.IsNullOrEmpty(academicNeeds))
            {
                //Do Nothing
            }

            academic.Add(academicNeeds);
            ViewBag.Academic = academic;

            return View(academic);
        }

        [HttpPost]
        public ActionResult input2(string educationalGoals)
        {
            List<string> schoolGoals = null;
            if (string.IsNullOrEmpty(educationalGoals))
            {
                //Do Nothing
            }

            schoolGoals.Add(educationalGoals);
            ViewBag.SchoolGoals = schoolGoals;

            return View(schoolGoals);
        }

        [HttpPost]
        public ActionResult input3(string careerGoals, string categorySelection)
        {
            List<string> career = null;
            List<string> careerType = null;
            if (string.IsNullOrEmpty(careerGoals))
            {
                //Do Nothing
            }


            career.Add(careerGoals);
            careerType.Add(categorySelection);
            ViewBag.Career = career;
            ViewBag.CareerType = careerType; 

            return View(career);
        }

        public ActionResult Print()
        {
            ViewBag.Message = "Print";

            return View();
        }

        /// <summary>
        /// Used to set all viewBags
        /// This was created because of multiple submit buttons on the page
        /// </summary>
        public void setViewBags()
        {
            //set the lists to a view bag
            ViewBag.Needs = needs;
            ViewBag.Education = education;
            ViewBag.CareerName = careerInputBox;
            ViewBag.CareerCategory = careerDropDown;
            ViewBag.StudentAdvisor = studentAdvisor;
            ViewBag.Academic = academic;
            ViewBag.SchoolGoals = schoolGoals;
            ViewBag.Career = career;
            ViewBag.CareerType = careerType;

            return;
        }
    }
}

GearUp/Views/LifePlan/Edit.cshtml
@model IEnumerable<GearUp.Models.Student>
@{
    ViewBag.Title = "LifePlan Edit";        
}

@* This is where the styling for this page is located. Look in Content folder for lifeplan-edit.css *@
<link href="~/Content/lifeplan-edit.css" rel="stylesheet" />

@* This is the container wrapped around our whole edit area *@
<div class="container">
    <br />
    @* Start of the Top Section (Search Bar and Advisor drop down) *@
    <div id="top-section" class="row">
        <div class="col-md-6">
            @using (@Html.BeginForm())
            {
                <b>Student Name: </b>
                @Html.TextBox("searchTerm", null, new { id = "txtStudentSearch" })
                <input class="btn btn-sm btn-primary" type="submit" name="submit" value="Search" />

            }﻿
        </div>
        <div class="col-md-6">
            <b>Advisor: </b>
            @if (ViewBag.StudentAdvisor == "")
            {
                @Html.TextBox("searchTerms", null, new { id = "txtAdvisorSearch" })
            }
            else
            { @Html.TextBox("serarchTerms", (string)ViewBag.StudentAdvisor, new { id = "txtAdvisorSearch" })}
        </div>
    </div>
    @* End of top section*@   
    <hr /> 
    <div class="row">

        @* Start of the Left Section (All of the input boxes, buttons, etc...) *@
        <div id="left-section" class="col-md-4">
            <div>
                
                @using (@Html.BeginForm("edit", "LifePlan", FormMethod.Post))
                {

                    @Html.Label("Academic Needs:") <br />
                    @Html.TextBox("academicNeeds");
                    <button class="btn btn-sm btn-primary" type="submit">Enter</button><br /> 
                  <div id="buttons">
                      <button class="btn btn-sm btn-default" type="reset">Clear</button>
                  </div>               
                }                      

            </div>
         <div id="output">
            <div class="panel panel-default">
                <div class="panel-body" id="output-area">
                    @*Academic Needs Stuff Goes Here...*@
                    @foreach (var academic in (List<string>)ViewBag.Academic)
                    {
                    <ul><li>@academic</li></ul>
                    }              
                </div>
            </div>
          </div>

            <div id="educational-goals">
                @using (@Html.BeginForm())
                {

                    @Html.Label("Educational Goals:") <br />
                    @Html.TextBox("educationalGoals")
                    <button type="submit">Enter</button><br />
                    <button class="btn btn-sm btn-primary" type="submit">Enter</button><br />
                    <div id="buttons">
                        <button type="reset">Clear</button>
                        <button class="btn btn-sm btn-default" type="reset">Clear</button>
                    </div>
                }
            </div>

            <div id="output">
                <div class="panel panel-default">
                    <div class="panel-body" id="output-area">
                        @*Education Goals Stuff Goes Here...*@

                        @foreach (var education in (List<string>)ViewBag.SchoolGoals)
                        {
                            <ul><li>@education</li></ul>
                        }

                    </div>
                </div>
            </div>
            <div id="career-goals">
                @using (@Html.BeginForm())
                {

                    @Html.Label("Career Goals:") <br />
                    @Html.TextBox("careerGoals")
                            <select id="categorySelection" name="categorySelection">
                                <option value=""></option>
                                <option selected="selected" value="0">Animal Science</option>
                                <option value="1">Auto/Aircraft Mechanics</option>
                                <option value="2">Business</option>
                                <option value="3">Communications</option>
                                <option value="4">Computers</option>
                                <option value="5">Construction</option>
                                <option value="6">Cosmetology</option>
                                <option value="7">Criminal Justice</option>
                                <option value="8">Culinary</option>
                                <option value="9">Education</option>
                                <option value="10">Engineering</option>
                                <option value="11">Entertainment</option>
                                <option value="12">Entrepreneurship</option>
                                <option value="13">Humanities</option>
                                <option value="14">Interior Design</option>
                                <option value="15">Medical/Dental</option>
                                <option value="16">Military</option>
                                <option value="17">Social Work/Psychology</option>
                                <option value="18">Visual/Performing Arts</option>
                                <option value="19">Other</option>
                            </select>
                        
                           
                        
                        <div id="buttons">
                            <button type="submit">Enter</button><br />
                            <button class="btn btn-sm btn-primary" type="submit">Enter</button><br />
                            <div id="clear">
                                <button type="reset">Clear</button>
                                <button class="btn btn-sm btn-default" type="reset">Clear</button>
                            </div>
                        </div>
                            

                }
            </div>

            <div id="career-output">
                <div class="panel panel-default">
                    <div class="panel-body" id="output-area">
                        @*Career Goals Stuff Goes Here...*@

                       @* if (((List<string>)ViewBag.Career) != null && ((List<string>)ViewBag.CareerType) != null)
                           {
                                List<string> name = (List<string>)ViewBag.Career;
                                List<string> category = (List<string>)ViewBag.CareerType;
                                List<string> output = new List<string>();

                                for (int i = 0; i < name.Count; i++)
                                {
                                    output.Add(name.ElementAt(i) + " / " + category.ElementAt(i));
                                }
                                foreach (var career in output)
                                {
                                    <ul><li>@career</li></ul>
                                }
                           }*@

                    </div>
                </div>
            </div>
            <div>
                <button class="btn btn-default">Cancel</button>
                <butoon class="btn btn-primary">Submit</butoon>
            </div>
        </div>
        @* End of left section *@

        @* Start of the right section (Where the boxes to display info are located) *@
        <div id="right-section" class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Academic Needs
                </div>
                <div class="panel-body">
                    @*academic needs Stuff Goes Here...*@
                    @foreach (var need in (List<string>)ViewBag.Needs)
                    {
                        <ul><li>@need</li></ul>
                    }
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Educational Goals
                </div>
                <div class="panel-body">
                    @*Educational Goals Stuff Goes Here...*@
                    @foreach (var education in (List<string>)ViewBag.Education)
                    {
                        <ul><li>@education</li></ul>
                    }
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Career Goals
                </div>
                <div class="panel-body">
                    @*Career Goals Stuff Goes Here...*@
                    @if (((List<string>)ViewBag.CareerName) != null && ((List<string>)ViewBag.CareerCategory) != null)
                    {
                        List<string> name = (List<string>)ViewBag.CareerName;
                        List<string> category = (List<string>)ViewBag.CareerCategory;
                        List<string> output = new List<string>();

                        for (int i = 0; i < name.Count; i++)
                        {
                            output.Add(name.ElementAt(i) + " / " + category.ElementAt(i));
                        }

                        foreach (var career in output)
                        {
                            <ul><li>@career</li></ul>
                        }
                    }
                </div>
            </div>

            <div>
                <form action="http://localhost:1662/LifePlan/Print">
                    <input class="btn btn-primary" type="submit" value="Print" />
                </form>
            </div>             
        </div>
        @* End of right section *@

    </div>
</div>

@*Script used for dropdown text boxes, should probably be moved to a
    global use location*@
<script type="text/javascript">
    $(document).ready(function () {
        $("#txtStudentSearch").autocomplete({
            source: '@Url.Action("GetStudents")',
            minLength: 1
        });
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#txtAdvisorSearch").autocomplete({
            source: '@Url.Action("GetAdvisors")',
            minLength: 1
        });
    });
</script>

@* End of container *@

GearUp/Views/LifePlan/Index.cshtml
@{
    ViewBag.Title = "LifePlan";
}

<h3>@ViewBag.Title</h3>
<h3>@ViewBag.Message</h3>

GearUp/Views/LifePlan/Print.cshtml
@*@model GearUp.Models.LifePlan*@ <!--These will need to be added in order to get the Model information to fill out the form once the database is connected-->
@*@model GearUp.Models.Contact*@
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Print";
    //var rowCounter = 0;
}

@* This is where the styling for this page is located. Look in Content folder for lifeplan-edit.css *@
<link href="~/Content/lifeplan-edit.css" rel="stylesheet" />

<style type="text/css">
    table {
        border: 1px solid black;
        border-collapse: collapse;
        text-align: left;
    }

    #col-1 {
        padding-left: 10px;
    }

    #col-2 {
        padding-left: 5px;
        word-wrap: break-word;    }

</style>



<h2>Student Life Plan</h2>



<table style="width:100%" border="1" id="table">
    <thead>
        <tr>
            <td id="col-1">Student Name:</td>
            <td colspan="2" id="col-1">
                @*@Model.Student.firstName + " " +
                @Model.Student.lastName*@
            </td>
        </tr>
        <tr>
            <td id="col-1">School:</td>
            <td colspan="2" id="col-1">
                @*@Model.School.name*@
            </td>
        </tr>
        <tr>
            <td id="col-1">Advisor:</td>
            <td colspan="2" id="col-1">
                @*@Model.Advisor.firstName + " " + @Model.Advisor.lastName*@
            </td>
        </tr>
        <tr>
            <td id="col-1">Grade:</td>
            <td colspan="2" id="col-1">
                @*@Model.Student.number*@
            </td>
        </tr>
        <tr>
            <td id="col-1">Date:</td>
            <td colspan="2" id="col-1">
                @DateTime.Today.ToString("MMMM dd, yyyy")
            </td>
        </tr>
        <tr>
            <td align="center">Academic Needs</td>
            <td align="center">Educational Goals</td>
            <td align="center">Career Goals/Category</td>
        </tr>
    </thead>
    <tbody>
        @{ 
            /*foreach (var item in Model)  //this will loop through each item stored in the model from the database for the given student
             *  and fill in the table accordingly-- the items names may change depending on database but the structure is correct
            {*/
            <tr>
                <td id="col-2">
                    @*@item.AcademicGoal*@  
                </td>
                <td id="col-2">
                    @*@item.EducationGoal*@
                </td>
                <td id="col-2">
                    @*@item.CareerGoal + "/" + item.Category*@
                </td>

            </tr>
                //rowCounter++;
            //}
        }
    </tbody>
</table>    
<a href="#" onclick="window.print(); return false;">Print</a>